version: "3.9"

services:
  btc_mon:
    env_file:
      - prod.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc_mon
    restart: unless-stopped
    volumes:
      - /tmp/cache/:/opt/btc_mon/cache

networks:
  default:
    name: btc_mon